<?php

return [
    'version' => '1.0',
    'envelope' => [
        'schema' => 'iam.n8n.envelope.v1',
        'fields' => [
            'event',
            'version',
            'occurred_at',
            'idempotency_key',
            'tenant_id',
            'actor',
            'subject',
            'context',
            'data',
            'links',
        ],
        'defaults' => [
            'version' => '1.0',
            'redaction_policy' => [
                'actor' => [
                    'email' => 'mask',
                    'ip' => 'remove',
                    'ua' => 'remove',
                ],
                'data' => [
                    'pii' => 'remove',
                ],
            ],
            'retention_days' => [
                'deliveries' => 30,
                'ai_reports' => 90,
                'security_events' => 180,
            ],
        ],
    ],
    'domains' => [
        'iam' => ['label_fa' => 'هویت و دسترسی'],
        'security' => ['label_fa' => 'امنیت'],
        'tenant' => ['label_fa' => 'مستاجر/سازمان'],
        'billing' => ['label_fa' => 'اشتراک و صورتحساب'],
        'wallet' => ['label_fa' => 'کیف پول'],
        'webhook' => ['label_fa' => 'وبهوک'],
        'automation' => ['label_fa' => 'اتوماسیون و هوش (n8n)'],
    ],
    'events' => [
        'iam.user.created' => [
            'label_fa' => 'ایجاد کاربر',
            'domain' => 'iam',
            'sensitivity' => 'medium',
            'default_enabled' => true,
        ],
        'iam.user.updated' => [
            'label_fa' => 'ویرایش کاربر',
            'domain' => 'iam',
            'sensitivity' => 'medium',
            'default_enabled' => true,
        ],
        'iam.user.deleted' => [
            'label_fa' => 'حذف کاربر',
            'domain' => 'iam',
            'sensitivity' => 'medium',
            'default_enabled' => true,
        ],
        'iam.membership.role.assigned' => [
            'label_fa' => 'انتصاب نقش',
            'domain' => 'iam',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
        'iam.membership.role.revoked' => [
            'label_fa' => 'لغو نقش',
            'domain' => 'iam',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
        'iam.permission.override.changed' => [
            'label_fa' => 'تغییر بازنویسی دسترسی',
            'domain' => 'iam',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
        'iam.access_request.created' => [
            'label_fa' => 'ایجاد درخواست دسترسی',
            'domain' => 'iam',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
        'iam.access_request.approved' => [
            'label_fa' => 'تایید درخواست دسترسی',
            'domain' => 'iam',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
        'iam.access_request.rejected' => [
            'label_fa' => 'رد درخواست دسترسی',
            'domain' => 'iam',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
        'security.auth.login.succeeded' => [
            'label_fa' => 'ورود موفق',
            'domain' => 'security',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
        'security.auth.login.failed' => [
            'label_fa' => 'ورود ناموفق',
            'domain' => 'security',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
        'security.auth.logout' => [
            'label_fa' => 'خروج',
            'domain' => 'security',
            'sensitivity' => 'medium',
            'default_enabled' => false,
        ],
        'security.otp.requested' => [
            'label_fa' => 'درخواست OTP',
            'domain' => 'security',
            'sensitivity' => 'high',
            'default_enabled' => false,
        ],
        'security.otp.verified' => [
            'label_fa' => 'تایید OTP',
            'domain' => 'security',
            'sensitivity' => 'high',
            'default_enabled' => false,
        ],
        'security.otp.failed' => [
            'label_fa' => 'خطای OTP',
            'domain' => 'security',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
        'security.impersonation.started' => [
            'label_fa' => 'شروع امپرسونیشن',
            'domain' => 'security',
            'sensitivity' => 'critical',
            'default_enabled' => true,
        ],
        'security.impersonation.stopped' => [
            'label_fa' => 'پایان امپرسونیشن',
            'domain' => 'security',
            'sensitivity' => 'critical',
            'default_enabled' => true,
        ],
        'security.api_key.created' => [
            'label_fa' => 'ایجاد کلید API',
            'domain' => 'security',
            'sensitivity' => 'critical',
            'default_enabled' => true,
        ],
        'security.api_key.rotated' => [
            'label_fa' => 'چرخش کلید API',
            'domain' => 'security',
            'sensitivity' => 'critical',
            'default_enabled' => true,
        ],
        'security.api_key.revoked' => [
            'label_fa' => 'ابطال کلید API',
            'domain' => 'security',
            'sensitivity' => 'critical',
            'default_enabled' => true,
        ],
        'wallet.transaction.created' => [
            'label_fa' => 'ایجاد تراکنش کیف پول',
            'domain' => 'wallet',
            'sensitivity' => 'high',
            'default_enabled' => false,
        ],
        'subscription.created' => [
            'label_fa' => 'ایجاد اشتراک',
            'domain' => 'billing',
            'sensitivity' => 'medium',
            'default_enabled' => false,
        ],
        'subscription.renewed' => [
            'label_fa' => 'تمدید اشتراک',
            'domain' => 'billing',
            'sensitivity' => 'medium',
            'default_enabled' => false,
        ],
        'subscription.canceled' => [
            'label_fa' => 'لغو اشتراک',
            'domain' => 'billing',
            'sensitivity' => 'medium',
            'default_enabled' => false,
        ],
        'webhook.delivery.failed' => [
            'label_fa' => 'شکست ارسال وبهوک',
            'domain' => 'webhook',
            'sensitivity' => 'medium',
            'default_enabled' => true,
        ],
        'webhook.health.degraded' => [
            'label_fa' => 'افت سلامت وبهوک',
            'domain' => 'webhook',
            'sensitivity' => 'medium',
            'default_enabled' => true,
        ],
        'automation.n8n.audit.run.started' => [
            'label_fa' => 'شروع حسابرسی هوشمند',
            'domain' => 'automation',
            'sensitivity' => 'low',
            'default_enabled' => true,
        ],
        'automation.n8n.audit.run.completed' => [
            'label_fa' => 'پایان حسابرسی هوشمند',
            'domain' => 'automation',
            'sensitivity' => 'medium',
            'default_enabled' => true,
        ],
        'automation.n8n.report.received' => [
            'label_fa' => 'دریافت گزارش هوش',
            'domain' => 'automation',
            'sensitivity' => 'medium',
            'default_enabled' => true,
        ],
        'automation.n8n.action_proposal.received' => [
            'label_fa' => 'دریافت پیشنهاد اقدام',
            'domain' => 'automation',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
        'automation.n8n.action_proposal.approved' => [
            'label_fa' => 'تایید پیشنهاد اقدام',
            'domain' => 'automation',
            'sensitivity' => 'critical',
            'default_enabled' => true,
        ],
        'automation.n8n.action_proposal.rejected' => [
            'label_fa' => 'رد پیشنهاد اقدام',
            'domain' => 'automation',
            'sensitivity' => 'critical',
            'default_enabled' => true,
        ],
        'automation.n8n.action_proposal.executed' => [
            'label_fa' => 'اجرای پیشنهاد اقدام',
            'domain' => 'automation',
            'sensitivity' => 'critical',
            'default_enabled' => true,
        ],
        'automation.n8n.callback.failed' => [
            'label_fa' => 'شکست دریافت Callback از n8n',
            'domain' => 'automation',
            'sensitivity' => 'high',
            'default_enabled' => true,
        ],
    ],
    'high_risk_action_dictionary' => [
        'refund_issued',
        'role_granted',
        'permission_changed',
        'api_key_rotated',
        'webhook_secret_rotated',
        'tenant_plan_changed',
        'wallet_withdraw_approved',
        'data_exported',
        'user_suspended',
    ],
    'default_subscriptions' => [
        'enabled_by_default' => [
            'security.auth.login.succeeded',
            'security.auth.login.failed',
            'security.otp.failed',
            'security.api_key.created',
            'security.api_key.rotated',
            'security.api_key.revoked',
            'security.impersonation.started',
            'security.impersonation.stopped',
            'iam.membership.role.assigned',
            'iam.membership.role.revoked',
            'iam.permission.override.changed',
            'iam.access_request.created',
            'iam.access_request.approved',
            'iam.access_request.rejected',
            'webhook.delivery.failed',
            'webhook.health.degraded',
            'automation.n8n.report.received',
        ],
        'opt_in' => [
            'subscription.created',
            'subscription.renewed',
            'subscription.canceled',
            'wallet.transaction.created',
        ],
    ],
];
