<?php

declare(strict_types=1);

namespace Filamat\IamSuite\Support;

final class PermissionLabels
{
    /**
     * @return array<string, string>
     */
    public static function labels(): array
    {
        return [
            'iam.view' => 'مشاهده مدیریت دسترسی',
            'iam.manage' => 'مدیریت کامل دسترسی',
            'organization.view' => 'مشاهده سازمان',
            'organization.manage' => 'مدیریت سازمان',
            'tenant.view' => 'مشاهده فضای کاری',
            'tenant.manage' => 'مدیریت فضای کاری',
            'user.view' => 'مشاهده کاربران',
            'user.manage' => 'مدیریت کاربران',
            'user.invite' => 'دعوت کاربر',
            'user.suspend' => 'تعلیق کاربر',
            'user.activate' => 'فعال‌سازی کاربر',
            'user.impersonate' => 'امپرسونیشن کاربر',
            'iam.impersonate' => 'شروع امپرسونیشن',
            'iam.impersonate.cross_tenant' => 'امپرسونیشن بین فضای کاری',
            'iam.impersonate.write' => 'امپرسونیشن با دسترسی نوشتن',
            'user.reset_otp' => 'ریست OTP کاربر',
            'role.view' => 'مشاهده نقش‌ها',
            'role.manage' => 'مدیریت نقش‌ها',
            'permission.view' => 'مشاهده مجوزها',
            'permission.manage' => 'مدیریت مجوزها',
            'group.view' => 'مشاهده گروه‌ها',
            'group.manage' => 'مدیریت گروه‌ها',
            'permission_template.view' => 'مشاهده قالب‌های مجوز',
            'permission_template.manage' => 'مدیریت قالب‌های مجوز',
            'permission_override.view' => 'مشاهده بازنویسی مجوز',
            'permission_override.manage' => 'مدیریت بازنویسی مجوز',
            'access_request.view' => 'مشاهده درخواست دسترسی',
            'access_request.manage' => 'مدیریت درخواست دسترسی',
            'access_request.approve' => 'تایید درخواست دسترسی',
            'access_request.deny' => 'رد درخواست دسترسی',
            'permission_snapshot.view' => 'مشاهده اسنپ‌شات دسترسی',
            'permission_snapshot.capture' => 'ثبت اسنپ‌شات دسترسی',
            'permission_snapshot.diff' => 'مقایسه اسنپ‌شات دسترسی',
            'delegated_admin.view' => 'مشاهده ادمین تفویض‌شده',
            'delegated_admin.manage' => 'مدیریت ادمین تفویض‌شده',
            'wallet.view' => 'مشاهده کیف پول',
            'wallet.manage' => 'مدیریت کیف پول',
            'wallet.credit' => 'افزایش موجودی کیف پول',
            'wallet.debit' => 'کاهش موجودی کیف پول',
            'wallet.hold' => 'هولد موجودی کیف پول',
            'wallet.capture' => 'تسویه هولد کیف پول',
            'wallet.release' => 'آزادسازی هولد کیف پول',
            'wallet.transfer' => 'انتقال کیف پول',
            'wallet.export' => 'خروجی کیف پول',
            'wallet_transaction.view' => 'مشاهده تراکنش‌های کیف پول',
            'wallet_transaction.export' => 'خروجی تراکنش‌های کیف پول',
            'wallet_hold.view' => 'مشاهده هولدهای کیف پول',
            'wallet_hold.manage' => 'مدیریت هولدهای کیف پول',
            'subscription.view' => 'مشاهده اشتراک‌ها',
            'subscription.manage' => 'مدیریت اشتراک‌ها',
            'subscription.cancel' => 'لغو اشتراک',
            'subscription.renew' => 'تمدید اشتراک',
            'subscription_plan.view' => 'مشاهده پلن‌ها',
            'subscription_plan.manage' => 'مدیریت پلن‌ها',
            'notification.view' => 'مشاهده اعلان‌ها',
            'notification.send' => 'ارسال اعلان',
            'notification.manage' => 'مدیریت اعلان‌ها',
            'webhook.view' => 'مشاهده وبهوک‌ها',
            'webhook.manage' => 'مدیریت وبهوک‌ها',
            'automation.view' => 'مشاهده اتوماسیون n8n',
            'automation.manage' => 'مدیریت اتوماسیون n8n',
            'automation.reports.view' => 'مشاهده گزارش‌های هوش',
            'automation.actions.view' => 'مشاهده پیشنهادهای اقدام هوش',
            'automation.actions.manage' => 'مدیریت پیشنهادهای اقدام هوش',
            'ai.manage' => 'مدیریت تنظیمات هوش مصنوعی',
            'ai.audit.view' => 'مشاهده لاگ و گزارش‌های هوش',
            'api.view' => 'مشاهده API',
            'api.manage' => 'مدیریت API',
            'api.key.manage' => 'مدیریت کلید API',
            'api.docs.view' => 'مشاهده مستندات API',
            'api.docs.manage' => 'مدیریت مستندات API',
            'security.view' => 'مشاهده امنیت',
            'security.manage' => 'مدیریت امنیت',
            'audit.view' => 'مشاهده ممیزی',
            'settings.manage' => 'مدیریت تنظیمات',
            'quick_actions.view' => 'مشاهده اقدامات سریع',
            'quick_actions.manage' => 'مدیریت اقدامات سریع',
            'pam.view' => 'مشاهده دسترسی ممتاز',
            'pam.manage' => 'مدیریت دسترسی ممتاز',
            'pam.request' => 'درخواست دسترسی ممتاز',
            'pam.approve' => 'تایید/رد دسترسی ممتاز',
            'pam.activate' => 'فعال‌سازی دسترسی ممتاز',
            'pam.revoke' => 'لغو دسترسی ممتاز',
            'session.view' => 'مشاهده نشست‌ها',
            'session.manage' => 'مدیریت نشست‌ها',
            'session.revoke' => 'ابطال نشست‌ها',
            'mfa.view' => 'مشاهده احراز هویت دومرحله‌ای',
            'mfa.manage' => 'مدیریت احراز هویت دومرحله‌ای',
            'mfa.reset' => 'ریست احراز هویت دومرحله‌ای',
            'sso.view' => 'مشاهده ورود یکپارچه',
            'sso.manage' => 'مدیریت ورود یکپارچه',
            'scim.view' => 'مشاهده SCIM',
            'scim.manage' => 'مدیریت SCIM',
            'accounting.view' => 'مشاهده حسابداری ایران',
            'accounting.company.view' => 'مشاهده شرکت‌های حسابداری',
            'accounting.company.manage' => 'مدیریت شرکت‌های حسابداری',
            'accounting.company_settings.view' => 'مشاهده تنظیمات شرکت حسابداری',
            'accounting.company_settings.manage' => 'مدیریت تنظیمات شرکت حسابداری',
            'accounting.branch.view' => 'مشاهده شعبه‌های حسابداری',
            'accounting.branch.manage' => 'مدیریت شعبه‌های حسابداری',
            'accounting.fiscal_year.view' => 'مشاهده سال‌های مالی',
            'accounting.fiscal_year.manage' => 'مدیریت سال‌های مالی',
            'accounting.account_plan.view' => 'مشاهده پلن‌های کدینگ',
            'accounting.account_plan.manage' => 'مدیریت پلن‌های کدینگ',
            'accounting.chart_account.view' => 'مشاهده کدینگ حساب‌ها',
            'accounting.chart_account.manage' => 'مدیریت کدینگ حساب‌ها',
            'accounting.dimension.view' => 'مشاهده ابعاد حسابداری',
            'accounting.dimension.manage' => 'مدیریت ابعاد حسابداری',
            'accounting.party.view' => 'مشاهده اشخاص',
            'accounting.party.manage' => 'مدیریت اشخاص',
            'accounting.product.view' => 'مشاهده کالا/خدمت',
            'accounting.product.manage' => 'مدیریت کالا/خدمت',
            'accounting.tax_category.view' => 'مشاهده دسته‌های مالیاتی',
            'accounting.tax_category.manage' => 'مدیریت دسته‌های مالیاتی',
            'accounting.uom.view' => 'مشاهده واحدهای اندازه‌گیری',
            'accounting.uom.manage' => 'مدیریت واحدهای اندازه‌گیری',
            'accounting.tax_rate.view' => 'مشاهده نرخ‌های مالیاتی',
            'accounting.tax_rate.manage' => 'مدیریت نرخ‌های مالیاتی',
            'accounting.vat_period.view' => 'مشاهده دوره‌های ارزش افزوده',
            'accounting.vat_period.manage' => 'مدیریت دوره‌های ارزش افزوده',
            'accounting.vat_report.view' => 'مشاهده گزارش ارزش افزوده',
            'accounting.vat_report.manage' => 'مدیریت گزارش ارزش افزوده',
            'accounting.withholding_rate.view' => 'مشاهده نرخ‌های تکلیفی',
            'accounting.withholding_rate.manage' => 'مدیریت نرخ‌های تکلیفی',
            'accounting.seasonal_report.view' => 'مشاهده گزارش معاملات فصلی',
            'accounting.seasonal_report.manage' => 'مدیریت گزارش معاملات فصلی',
            'accounting.journal.view' => 'مشاهده اسناد حسابداری',
            'accounting.journal.create' => 'ایجاد سند حسابداری',
            'accounting.journal.submit' => 'ارسال سند برای تایید',
            'accounting.journal.approve' => 'تایید سند حسابداری',
            'accounting.journal.post' => 'ثبت قطعی سند حسابداری',
            'accounting.journal.reverse' => 'ثبت سند اصلاحی/معکوس',
            'accounting.journal.void' => 'ابطال سند حسابداری',
            'accounting.journal.export' => 'خروجی اسناد حسابداری',
            'accounting.period.lock' => 'قفل دوره مالی',
            'accounting.period.unlock' => 'بازکردن قفل دوره مالی',
            'accounting.sales.view' => 'مشاهده فروش',
            'accounting.sales.manage' => 'مدیریت فروش',
            'accounting.purchase.view' => 'مشاهده خرید',
            'accounting.purchase.manage' => 'مدیریت خرید',
            'accounting.treasury.view' => 'مشاهده خزانه',
            'accounting.treasury.manage' => 'مدیریت خزانه',
            'accounting.inventory.view' => 'مشاهده انبار',
            'accounting.inventory.manage' => 'مدیریت انبار',
            'accounting.inventory.post' => 'ثبت سند انبار',
            'accounting.fixed_assets.view' => 'مشاهده دارایی‌های ثابت',
            'accounting.fixed_assets.manage' => 'مدیریت دارایی‌های ثابت',
            'accounting.payroll.view' => 'مشاهده حقوق و دستمزد',
            'accounting.payroll.manage' => 'مدیریت حقوق و دستمزد',
            'accounting.project.view' => 'مشاهده پروژه‌های پیمانکاری',
            'accounting.project.manage' => 'مدیریت پروژه‌های پیمانکاری',
            'accounting.contract.view' => 'مشاهده قراردادها',
            'accounting.contract.manage' => 'مدیریت قراردادها',
            'accounting.tax.view' => 'مشاهده مالیات',
            'accounting.tax.manage' => 'مدیریت مالیات',
            'accounting.tax.submit' => 'ارسال گزارش مالیاتی',
            'accounting.einvoice.view' => 'مشاهده صورتحساب الکترونیکی',
            'accounting.einvoice.manage' => 'مدیریت صورتحساب الکترونیکی',
            'accounting.einvoice.send' => 'ارسال صورتحساب الکترونیکی',
            'accounting.einvoice.retry' => 'تلاش مجدد ارسال صورتحساب الکترونیکی',
            'accounting.einvoice.keys.manage' => 'مدیریت کلیدهای سامانه مؤدیان',
            'accounting.report.view' => 'مشاهده گزارش‌های حسابداری',
            'accounting.report.export' => 'خروجی گزارش‌های حسابداری',
            'accounting.integration.view' => 'مشاهده یکپارچه‌سازی‌ها',
            'accounting.integration.manage' => 'مدیریت یکپارچه‌سازی‌ها',
            'workhub.project.view' => 'مشاهده پروژه‌ها',
            'workhub.project.manage' => 'مدیریت پروژه‌ها',
            'workhub.work_item.view' => 'مشاهده آیتم‌های کاری',
            'workhub.work_item.manage' => 'مدیریت آیتم‌های کاری',
            'workhub.workflow.view' => 'مشاهده گردش‌کارها',
            'workhub.workflow.manage' => 'مدیریت گردش‌کارها',
            'workhub.status.view' => 'مشاهده وضعیت‌ها',
            'workhub.status.manage' => 'مدیریت وضعیت‌ها',
            'workhub.transition.view' => 'مشاهده انتقال‌ها',
            'workhub.transition.manage' => 'مدیریت انتقال‌ها',
            'workhub.work_type.view' => 'مشاهده نوع‌های کار',
            'workhub.work_type.manage' => 'مدیریت نوع‌های کار',
            'workhub.comment.view' => 'مشاهده دیدگاه‌ها',
            'workhub.comment.manage' => 'مدیریت دیدگاه‌ها',
            'workhub.attachment.view' => 'مشاهده پیوست‌ها',
            'workhub.attachment.manage' => 'مدیریت پیوست‌ها',
            'workhub.watcher.view' => 'مشاهده دنبال‌کننده‌ها',
            'workhub.watcher.manage' => 'مدیریت دنبال‌کننده‌ها',
            'workhub.label.view' => 'مشاهده برچسب‌ها',
            'workhub.label.manage' => 'مدیریت برچسب‌ها',
            'workhub.time_entry.view' => 'مشاهده زمان‌ها',
            'workhub.time_entry.manage' => 'مدیریت زمان‌ها',
            'workhub.decision.view' => 'مشاهده تصمیم‌ها',
            'workhub.decision.manage' => 'مدیریت تصمیم‌ها',
            'workhub.audit.view' => 'مشاهده ممیزی کارها',
            'workhub.automation.view' => 'مشاهده اتوماسیون',
            'workhub.automation.manage' => 'مدیریت اتوماسیون',
            'workhub.custom_field.view' => 'مشاهده فیلدهای سفارشی',
            'workhub.custom_field.manage' => 'مدیریت فیلدهای سفارشی',
            'workhub.link.view' => 'مشاهده لینک‌ها',
            'workhub.link.manage' => 'مدیریت لینک‌ها',
            'workhub.ai.use' => 'استفاده از هوش مصنوعی',
            'workhub.ai.share' => 'اشتراک‌گذاری خروجی هوش مصنوعی',
            'workhub.ai.fields.manage' => 'مدیریت فیلدهای هوش مصنوعی',
            'workhub.ai.project_reports.manage' => 'مدیریت گزارش‌های هوش پروژه',
            'meetings.view' => 'مشاهده جلسات',
            'meetings.manage' => 'مدیریت جلسات',
            'meetings.templates.manage' => 'مدیریت قالب‌های جلسه',
            'meetings.transcript.manage' => 'مدیریت متن جلسه',
            'meetings.minutes.manage' => 'مدیریت صورتجلسه',
            'meetings.ai.use' => 'استفاده از هوش مصنوعی جلسات',
            'meetings.ai.manage' => 'مدیریت هوش مصنوعی جلسات',
            'meetings.action_items.manage' => 'مدیریت اقدام‌های جلسه',
            'meetings.share.manage' => 'مدیریت اشتراک صورتجلسه',
            'esim_go.connection.view' => 'مشاهده اتصال eSIM Go',
            'esim_go.connection.manage' => 'مدیریت اتصال eSIM Go',
            'esim_go.catalogue.view' => 'مشاهده کاتالوگ eSIM Go',
            'esim_go.catalogue.sync' => 'همگام‌سازی کاتالوگ eSIM Go',
            'esim_go.product.view' => 'مشاهده محصولات eSIM Go',
            'esim_go.product.manage' => 'مدیریت محصولات eSIM Go',
            'esim_go.order.view' => 'مشاهده سفارش‌های eSIM Go',
            'esim_go.order.manage' => 'مدیریت سفارش‌های eSIM Go',
            'esim_go.fulfillment.view' => 'مشاهده تحویل eSIM Go',
            'esim_go.webhook.view' => 'مشاهده وبهوک eSIM Go',
            'esim_go.inventory.view' => 'مشاهده موجودی eSIM Go',
            'esim_go.inventory.refund' => 'بازپرداخت موجودی eSIM Go',
            'mailtrap.connection.view' => 'مشاهده اتصال Mailtrap',
            'mailtrap.connection.manage' => 'مدیریت اتصال Mailtrap',
            'mailtrap.inbox.view' => 'مشاهده Inboxهای Mailtrap',
            'mailtrap.inbox.sync' => 'همگام‌سازی Inboxهای Mailtrap',
            'mailtrap.inbox.manage' => 'مدیریت Inboxهای Mailtrap',
            'mailtrap.message.view' => 'مشاهده پیام‌های Mailtrap',
            'mailtrap.domain.view' => 'مشاهده دامنه‌های Mailtrap',
            'mailtrap.domain.sync' => 'همگام‌سازی دامنه‌های Mailtrap',
            'mailtrap.domain.manage' => 'مدیریت دامنه‌های Mailtrap',
            'mailtrap.offer.view' => 'مشاهده پکیج‌های Mailtrap',
            'mailtrap.offer.manage' => 'مدیریت پکیج‌های Mailtrap',
            'mailtrap.send.test' => 'تست ارسال Mailtrap',
            'mailtrap.send.single' => 'ارسال ایمیل تکی (Mailtrap)',
            'mailtrap.audience.view' => 'مشاهده مخاطبان ایمیل',
            'mailtrap.audience.manage' => 'مدیریت مخاطبان ایمیل',
            'mailtrap.campaign.view' => 'مشاهده کمپین‌های ایمیلی',
            'mailtrap.campaign.manage' => 'مدیریت کمپین‌های ایمیلی',
            'mailtrap.campaign.send' => 'ارسال کمپین‌های ایمیلی',
            'threecx.view' => 'مشاهده 3CX',
            'threecx.manage' => 'مدیریت 3CX',
            'threecx.sync' => 'همگام‌سازی 3CX',
            'threecx.api_explorer' => 'کاوشگر API 3CX',
            'threecx.crm_connector' => 'اتصال CRM 3CX',
            'loyalty.view' => 'مشاهده باشگاه مشتریان',
            'loyalty.customer.view' => 'مشاهده مشتریان باشگاه',
            'loyalty.customer.manage' => 'مدیریت مشتریان باشگاه',
            'loyalty.tier.view' => 'مشاهده سطوح وفاداری',
            'loyalty.tier.manage' => 'مدیریت سطوح وفاداری',
            'loyalty.rule.view' => 'مشاهده قوانین امتیاز',
            'loyalty.rule.manage' => 'مدیریت قوانین امتیاز',
            'loyalty.reward.view' => 'مشاهده پاداش‌ها',
            'loyalty.reward.manage' => 'مدیریت پاداش‌ها',
            'loyalty.reward.redeem' => 'بازخرید پاداش',
            'loyalty.coupon.view' => 'مشاهده کوپن‌ها',
            'loyalty.coupon.manage' => 'مدیریت کوپن‌ها',
            'loyalty.coupon.issue' => 'صدور کوپن',
            'loyalty.coupon.redeem' => 'بازخرید کوپن',
            'loyalty.referral.view' => 'مشاهده معرفی‌ها',
            'loyalty.referral.manage' => 'مدیریت معرفی‌ها',
            'loyalty.referral.program.view' => 'مشاهده برنامه‌های معرفی',
            'loyalty.referral.program.manage' => 'مدیریت برنامه‌های معرفی',
            'loyalty.mission.view' => 'مشاهده ماموریت‌ها',
            'loyalty.mission.manage' => 'مدیریت ماموریت‌ها',
            'loyalty.badge.view' => 'مشاهده نشان‌ها',
            'loyalty.badge.manage' => 'مدیریت نشان‌ها',
            'loyalty.segment.view' => 'مشاهده بخش‌بندی',
            'loyalty.segment.manage' => 'مدیریت بخش‌بندی',
            'loyalty.campaign.view' => 'مشاهده کمپین‌ها',
            'loyalty.campaign.manage' => 'مدیریت کمپین‌ها',
            'loyalty.campaign.send' => 'ارسال کمپین',
            'loyalty.fraud.view' => 'مشاهده هشدارهای تقلب',
            'loyalty.fraud.manage' => 'مدیریت هشدارهای تقلب',
            'loyalty.audit.view' => 'مشاهده ممیزی باشگاه',
            'loyalty.event.ingest' => 'دریافت رویداد باشگاه',
            'loyalty.settings.manage' => 'مدیریت تنظیمات باشگاه',
            'loyalty.ai.use' => 'استفاده از هوش مصنوعی باشگاه',
            'loyalty.ai.manage' => 'مدیریت هوش مصنوعی باشگاه',
            'app.view' => 'مشاهده اپلیکیشن‌ها',
            'app.config.view' => 'مشاهده پیکربندی اپلیکیشن',
            'app.sync' => 'همگام‌سازی اپلیکیشن',
            'app.device.manage' => 'مدیریت دستگاه‌های اپلیکیشن',
            'app.notification.view' => 'مشاهده اعلان‌های اپلیکیشن',
            'app.notification.manage' => 'مدیریت اعلان‌های اپلیکیشن',
            'app.tenant.view' => 'مشاهده فضای کاری اپلیکیشن',
            'app.tenant.switch' => 'تغییر فضای کاری اپلیکیشن',
            'app.realtime.signal' => 'سیگنالینگ بلادرنگ اپلیکیشن',
            'support.ticket.view' => 'مشاهده تیکت‌های پشتیبانی',
            'support.ticket.manage' => 'مدیریت تیکت‌های پشتیبانی',
            'support.message.view' => 'مشاهده پیام‌های پشتیبانی',
            'support.message.manage' => 'مدیریت پیام‌های پشتیبانی',
            'support.attachment.manage' => 'مدیریت پیوست‌های پشتیبانی',
            'payroll.view' => 'مشاهده منابع انسانی و حضور و غیاب',
            'payroll.employee.view' => 'مشاهده پرسنل',
            'payroll.employee.manage' => 'مدیریت پرسنل',
            'payroll.contract.view' => 'مشاهده قراردادها',
            'payroll.contract.manage' => 'مدیریت قراردادها',
            'payroll.shift.view' => 'مشاهده شیفت‌ها',
            'payroll.shift.manage' => 'مدیریت شیفت‌ها',
            'payroll.schedule.view' => 'مشاهده برنامه‌های حضور',
            'payroll.schedule.manage' => 'مدیریت برنامه‌های حضور',
            'payroll.punch.view' => 'مشاهده ترددها',
            'payroll.punch.manage' => 'مدیریت ترددها',
            'payroll.time_event.view' => 'مشاهده رویدادهای زمانی',
            'payroll.time_event.manage' => 'مدیریت رویدادهای زمانی',
            'payroll.attendance.view' => 'مشاهده رکوردهای حضور',
            'payroll.attendance.manage' => 'مدیریت رکوردهای حضور',
            'payroll.attendance.approve' => 'تایید رکوردهای حضور',
            'payroll.attendance.lock' => 'قفل رکوردهای حضور',
            'payroll.timesheet.view' => 'مشاهده کاربرگ‌ها',
            'payroll.timesheet.manage' => 'مدیریت کاربرگ‌ها',
            'payroll.timesheet.approve' => 'تایید کاربرگ‌ها',
            'payroll.exception.view' => 'مشاهده استثناهای حضور',
            'payroll.exception.manage' => 'مدیریت استثناهای حضور',
            'payroll.exception.resolve' => 'رفع استثناهای حضور',
            'payroll.policy.view' => 'مشاهده سیاست‌های حضور و غیاب',
            'payroll.policy.manage' => 'مدیریت سیاست‌های حضور و غیاب',
            'payroll.calendar.view' => 'مشاهده تقویم‌های کاری',
            'payroll.calendar.manage' => 'مدیریت تقویم‌های کاری',
            'payroll.leave.view' => 'مشاهده مرخصی‌ها',
            'payroll.leave.request' => 'ثبت درخواست مرخصی',
            'payroll.leave.approve' => 'تایید مرخصی‌ها',
            'payroll.leave.manage' => 'مدیریت مرخصی‌ها',
            'payroll.mission.view' => 'مشاهده ماموریت‌ها',
            'payroll.mission.request' => 'ثبت درخواست ماموریت',
            'payroll.mission.approve' => 'تایید ماموریت‌ها',
            'payroll.mission.manage' => 'مدیریت ماموریت‌ها',
            'payroll.overtime.view' => 'مشاهده اضافه‌کارها',
            'payroll.overtime.request' => 'ثبت درخواست اضافه‌کار',
            'payroll.overtime.approve' => 'تایید اضافه‌کارها',
            'payroll.overtime.manage' => 'مدیریت اضافه‌کارها',
            'payroll.run.view' => 'مشاهده ران حقوق',
            'payroll.run.manage' => 'مدیریت ران حقوق',
            'payroll.run.approve' => 'تایید ران حقوق',
            'payroll.run.post' => 'ثبت قطعی ران حقوق',
            'payroll.run.lock' => 'قفل ران حقوق',
            'payroll.slip.view' => 'مشاهده فیش حقوق',
            'payroll.loan.manage' => 'مدیریت وام‌های پرسنلی',
            'payroll.advance.manage' => 'مدیریت مساعده‌ها',
            'payroll.settings.view' => 'مشاهده تنظیمات حقوق',
            'payroll.settings.manage' => 'مدیریت تنظیمات حقوق',
            'payroll.report.view' => 'مشاهده گزارش‌های حضور و غیاب',
            'payroll.report.export' => 'خروجی گزارش‌های حضور و غیاب',
            'payroll.consent.view' => 'مشاهده رضایت‌نامه‌ها',
            'payroll.consent.manage' => 'مدیریت رضایت‌نامه‌ها',
            'payroll.audit.view' => 'مشاهده لاگ‌های ممیزی حضور',
            'payroll.ai.view' => 'مشاهده لاگ‌های هوش مصنوعی حضور',
            'payroll.ai.use' => 'استفاده از هوش مصنوعی حضور',
        ];
    }

    public static function label(string $permissionKey): string
    {
        $labels = self::labels();
        if (isset($labels[$permissionKey])) {
            return $labels[$permissionKey];
        }

        $fallback = self::fallbackLabel($permissionKey);

        return $fallback ?: $permissionKey;
    }

    public static function labelWithKey(string $permissionKey): string
    {
        $label = self::label($permissionKey);

        if ($label === $permissionKey) {
            return $permissionKey;
        }

        return $label.' ('.$permissionKey.')';
    }

    /**
     * @param  array<int, string>  $permissions
     * @return array<string, string>
     */
    public static function optionLabels(array $permissions): array
    {
        $options = [];

        foreach ($permissions as $permissionKey) {
            $options[$permissionKey] = self::labelWithKey($permissionKey);
        }

        return $options;
    }

    protected static function fallbackLabel(string $permissionKey): ?string
    {
        $parts = explode('.', $permissionKey);
        if (count($parts) < 2) {
            return null;
        }

        $action = array_pop($parts);
        $domainKey = implode('.', $parts);

        $domainLabel = self::domainLabel($domainKey) ?? self::domainLabel($parts[0]);
        $actionLabel = self::actionLabel($action);

        if (! $domainLabel || ! $actionLabel) {
            return null;
        }

        return trim($actionLabel.' '.$domainLabel);
    }

    protected static function domainLabel(string $domainKey): ?string
    {
        return match ($domainKey) {
            'api.docs' => 'مستندات API',
            'api.key' => 'کلید API',
            'iam' => 'مدیریت دسترسی',
            'organization' => 'سازمان',
            'tenant' => 'فضای کاری',
            'user' => 'کاربر',
            'role' => 'نقش',
            'permission' => 'مجوز',
            'group' => 'گروه',
            'permission_template' => 'قالب مجوز',
            'permission_override' => 'بازنویسی مجوز',
            'access_request' => 'درخواست دسترسی',
            'permission_snapshot' => 'اسنپ‌شات دسترسی',
            'delegated_admin' => 'ادمین تفویض‌شده',
            'wallet' => 'کیف پول',
            'wallet_transaction' => 'تراکنش کیف پول',
            'wallet_hold' => 'هولد کیف پول',
            'subscription' => 'اشتراک',
            'subscription_plan' => 'پلن اشتراک',
            'notification' => 'اعلان',
            'webhook' => 'وبهوک',
            'ai' => 'هوش مصنوعی',
            'api' => 'API',
            'security' => 'امنیت',
            'audit' => 'ممیزی',
            'settings' => 'تنظیمات',
            'accounting' => 'حسابداری',
            'accounting.company' => 'شرکت حسابداری',
            'accounting.company_settings' => 'تنظیمات شرکت حسابداری',
            'accounting.branch' => 'شعبه حسابداری',
            'accounting.fiscal_year' => 'سال مالی',
            'accounting.account_plan' => 'پلن کدینگ',
            'accounting.chart_account' => 'کدینگ حساب',
            'accounting.dimension' => 'ابعاد حسابداری',
            'accounting.party' => 'اشخاص',
            'accounting.product' => 'کالا/خدمت',
            'accounting.tax_category' => 'دسته مالیاتی',
            'accounting.uom' => 'واحد اندازه‌گیری',
            'accounting.tax_rate' => 'نرخ مالیاتی',
            'accounting.vat_period' => 'دوره ارزش افزوده',
            'accounting.vat_report' => 'گزارش ارزش افزوده',
            'accounting.withholding_rate' => 'نرخ تکلیفی',
            'accounting.seasonal_report' => 'گزارش معاملات فصلی',
            'accounting.journal' => 'سند حسابداری',
            'accounting.period' => 'دوره مالی',
            'accounting.sales' => 'فروش',
            'accounting.purchase' => 'خرید',
            'accounting.treasury' => 'خزانه',
            'accounting.inventory' => 'انبار',
            'accounting.fixed_assets' => 'دارایی ثابت',
            'accounting.payroll' => 'حقوق و دستمزد',
            'accounting.project' => 'پروژه',
            'accounting.contract' => 'قرارداد',
            'accounting.tax' => 'مالیات',
            'accounting.einvoice' => 'صورتحساب الکترونیکی',
            'accounting.report' => 'گزارش حسابداری',
            'accounting.integration' => 'یکپارچه‌سازی',
            'petty_cash' => 'تنخواه',
            'petty_cash.fund' => 'صندوق تنخواه',
            'petty_cash.category' => 'دسته هزینه',
            'petty_cash.expense' => 'هزینه تنخواه',
            'petty_cash.replenishment' => 'تغذیه تنخواه',
            'petty_cash.settlement' => 'تسویه تنخواه',
            'petty_cash.workflow' => 'گردش‌کار تنخواه',
            'petty_cash.controls.reconcile' => 'تطبیق تنخواه',
            'petty_cash.controls.cash_count' => 'شمارش نقدی تنخواه',
            'petty_cash.exceptions' => 'استثناهای تنخواه',
            'petty_cash.report' => 'گزارش تنخواه',
            'petty_cash.ai' => 'هوش مصنوعی تنخواه',
            'workhub' => 'رهگیری کارها',
            'workhub.project' => 'پروژه',
            'workhub.work_item' => 'آیتم کاری',
            'workhub.workflow' => 'گردش‌کار',
            'workhub.status' => 'وضعیت',
            'workhub.transition' => 'انتقال',
            'workhub.work_type' => 'نوع کار',
            'workhub.comment' => 'دیدگاه',
            'workhub.attachment' => 'پیوست',
            'workhub.watcher' => 'دنبال‌کننده',
            'workhub.label' => 'برچسب',
            'workhub.time_entry' => 'ثبت زمان',
            'workhub.decision' => 'تصمیم',
            'workhub.audit' => 'ممیزی کارها',
            'workhub.automation' => 'اتوماسیون',
            'workhub.custom_field' => 'فیلد سفارشی',
            'workhub.link' => 'لینک',
            'commerce' => 'تجارت',
            'commerce.catalog' => 'کاتالوگ',
            'commerce.catalog.view' => 'مشاهده کاتالوگ',
            'commerce.catalog.manage' => 'مدیریت کاتالوگ',
            'commerce.pricing' => 'قیمت گذاری',
            'commerce.pricing.view' => 'مشاهده قیمت گذاری',
            'commerce.pricing.manage' => 'مدیریت قیمت گذاری',
            'commerce.inventory' => 'موجودی',
            'commerce.inventory.view' => 'مشاهده موجودی',
            'commerce.inventory.manage' => 'مدیریت موجودی',
            'commerce.inventory.adjust' => 'تعدیل موجودی',
            'commerce.customers' => 'مشتریان',
            'commerce.customers.view' => 'مشاهده مشتریان',
            'commerce.customers.manage' => 'مدیریت مشتریان',
            'commerce.order' => 'سفارش‌ها',
            'commerce.order.view' => 'مشاهده سفارش‌ها',
            'commerce.order.manage' => 'مدیریت سفارش‌ها',
            'commerce.order.return' => 'مرجوعی‌ها',
            'commerce.order.return.view' => 'مشاهده مرجوعی‌ها',
            'commerce.order.return.manage' => 'مدیریت مرجوعی‌ها',
            'commerce.order.refund' => 'بازپرداخت‌ها',
            'commerce.order.refund.view' => 'مشاهده بازپرداخت‌ها',
            'commerce.order.refund.manage' => 'مدیریت بازپرداخت‌ها',
            'commerce.compliance' => 'انطباق و ضدتقلب',
            'commerce.compliance.view' => 'مشاهده انطباق',
            'commerce.compliance.manage' => 'مدیریت انطباق',
            'commerce.compliance.resolve' => 'حل پرونده‌های انطباق',
            'payments' => 'پرداخت‌ها',
            'payments.view' => 'مشاهده پرداخت‌ها',
            'payments.manage' => 'مدیریت پرداخت‌ها',
            'payments.webhooks' => 'وبهوک‌های پرداخت',
            'payments.webhooks.view' => 'مشاهده وبهوک‌های پرداخت',
            'payments.webhooks.manage' => 'مدیریت وبهوک‌های پرداخت',
            'crypto.accounts.view' => 'مشاهده حساب‌های رمزارز',
            'crypto.accounts.manage' => 'مدیریت حساب‌های رمزارز',
            'crypto.ledgers.view' => 'مشاهده دفترکل رمزارز',
            'crypto.ledgers.manage' => 'مدیریت دفترکل رمزارز',
            'crypto.ledger_entries.view' => 'مشاهده آرتیکل‌های دفترکل رمزارز',
            'crypto.ledger_entries.manage' => 'مدیریت آرتیکل‌های دفترکل رمزارز',
            'crypto.wallets.view' => 'مشاهده کیف‌پول‌های رمزارز',
            'crypto.wallets.manage' => 'مدیریت کیف‌پول‌های رمزارز',
            'crypto.addresses.view' => 'مشاهده آدرس‌های رمزارز',
            'crypto.addresses.manage' => 'مدیریت آدرس‌های رمزارز',
            'crypto.rates.view' => 'مشاهده نرخ‌های رمزارز',
            'crypto.rates.manage' => 'مدیریت نرخ‌های رمزارز',
            'crypto.network_fees.view' => 'مشاهده کارمزد شبکه رمزارز',
            'crypto.network_fees.manage' => 'مدیریت کارمزد شبکه رمزارز',
            'crypto.fee_policies.view' => 'مشاهده سیاست کارمزد رمزارز',
            'crypto.fee_policies.manage' => 'مدیریت سیاست کارمزد رمزارز',
            'crypto.providers.view' => 'مشاهده اتصال‌های درگاه رمزارز',
            'crypto.providers.manage' => 'مدیریت اتصال‌های درگاه رمزارز',
            'crypto.invoices.view' => 'مشاهده فاکتورهای رمزارز',
            'crypto.invoices.manage' => 'مدیریت فاکتورهای رمزارز',
            'crypto.invoice_payments.view' => 'مشاهده پرداخت‌های فاکتور رمزارز',
            'crypto.invoice_payments.manage' => 'مدیریت پرداخت‌های فاکتور رمزارز',
            'crypto.payouts.view' => 'مشاهده برداشت‌های رمزارز',
            'crypto.payouts.manage' => 'مدیریت برداشت‌های رمزارز',
            'crypto.payouts.approve' => 'تایید برداشت‌های رمزارز',
            'crypto.payout_destinations.view' => 'مشاهده لیست سفید برداشت رمزارز',
            'crypto.payout_destinations.manage' => 'مدیریت لیست سفید برداشت رمزارز',
            'crypto.webhooks.view' => 'مشاهده وبهوک‌های رمزارز',
            'crypto.webhooks.manage' => 'مدیریت وبهوک‌های رمزارز',
            'crypto.reconciliations.view' => 'مشاهده آشتی‌سازی رمزارز',
            'crypto.reconciliations.manage' => 'مدیریت آشتی‌سازی رمزارز',
            'crypto.ai_reports.view' => 'مشاهده گزارش‌های حسابرس رمزارز',
            'crypto.ai_reports.manage' => 'مدیریت گزارش‌های حسابرس رمزارز',
            'crypto.reconcile.run' => 'اجرای دستی آشتی‌سازی رمزارز',
            'crypto.nodes.view' => 'مشاهده نودهای رمزارز',
            'crypto.nodes.manage' => 'مدیریت نودهای رمزارز',
            'pos' => 'پوز',
            'pos.view' => 'مشاهده پوز',
            'pos.use' => 'استفاده از پوز',
            'pos.manage_register' => 'مدیریت صندوق‌ها و پایانه‌ها',
            'pos.manage_cash' => 'مدیریت صندوق نقدی',
            'pos.refund' => 'بازپرداخت پوز',
            'pos.void' => 'ابطال فروش پوز',
            'pos.override_discount' => 'دور زدن تخفیف پوز',
            'storebuilder' => 'سازنده فروشگاه',
            'storebuilder.view' => 'مشاهده سازنده فروشگاه',
            'storebuilder.manage' => 'مدیریت سازنده فروشگاه',
            'storebuilder.publish' => 'انتشار صفحات فروشگاه',
            'experience' => 'تجربه مشتری',
            'experience.reviews.view' => 'مشاهده نظرات و پرسش‌ها',
            'experience.reviews.moderate' => 'مدیریت و تایید نظرات',
            'experience.csat.view' => 'مشاهده CSAT/NPS',
            'experience.csat.manage' => 'مدیریت CSAT/NPS',
            'experience.buy_now.manage' => 'مدیریت خرید فوری',
            'marketplace' => 'مارکت‌پلیس',
            'marketplace.connectors.manage' => 'مدیریت اتصال مارکت‌پلیس',
            'marketplace.connectors.sync' => 'همگام‌سازی مارکت‌پلیس',
            'threecx' => '3CX',
            'loyalty' => 'باشگاه مشتریان',
            'loyalty.customer' => 'مشتریان باشگاه',
            'loyalty.tier' => 'سطوح وفاداری',
            'loyalty.rule' => 'قوانین امتیاز',
            'loyalty.reward' => 'پاداش‌ها',
            'loyalty.coupon' => 'کوپن‌ها',
            'loyalty.referral' => 'معرفی‌ها',
            'loyalty.referral.program' => 'برنامه‌های معرفی',
            'loyalty.mission' => 'ماموریت‌ها',
            'loyalty.badge' => 'نشان‌ها',
            'loyalty.segment' => 'بخش‌بندی',
            'loyalty.campaign' => 'کمپین‌ها',
            'loyalty.fraud' => 'هشدارهای تقلب',
            'loyalty.audit' => 'ممیزی باشگاه',
            'loyalty.event' => 'رویدادهای باشگاه',
            'loyalty.settings' => 'تنظیمات باشگاه',
            'loyalty.ai' => 'هوش مصنوعی باشگاه',
            'app' => 'اپلیکیشن‌ها',
            'app.config' => 'پیکربندی اپلیکیشن',
            'app.sync' => 'همگام‌سازی اپلیکیشن',
            'app.device' => 'دستگاه‌های اپلیکیشن',
            'app.notification' => 'اعلان‌های اپلیکیشن',
            'app.tenant' => 'فضای کاری اپلیکیشن',
            'app.realtime' => 'بلادرنگ اپلیکیشن',
            'support' => 'پشتیبانی',
            'support.ticket' => 'تیکت پشتیبانی',
            'support.message' => 'پیام پشتیبانی',
            'support.attachment' => 'پیوست پشتیبانی',
            'mailops' => 'ایمیل',
            'mailops.domain' => 'دامنه ایمیل',
            'mailops.mailbox' => 'صندوق ایمیل',
            'mailops.alias' => 'نام مستعار ایمیل',
            'mailops.outbound' => 'ایمیل خروجی',
            'mailops.inbound' => 'ایمیل دریافتی',
            'mailops.settings' => 'تنظیمات ایمیل',
            default => null,
        };
    }

    protected static function actionLabel(string $action): ?string
    {
        return match ($action) {
            'view' => 'مشاهده',
            'manage' => 'مدیریت',
            'create' => 'ایجاد',
            'update' => 'ویرایش',
            'delete' => 'حذف',
            'invite' => 'دعوت',
            'suspend' => 'تعلیق',
            'activate' => 'فعال‌سازی',
            'impersonate' => 'امپرسونیشن',
            'reset_otp' => 'ریست OTP',
            'approve' => 'تایید',
            'submit' => 'ارسال',
            'post' => 'ثبت قطعی',
            'reject' => 'رد',
            'settle' => 'تسویه',
            'use' => 'استفاده',
            'view_reports' => 'مشاهده گزارش',
            'manage_settings' => 'مدیریت تنظیمات',
            'reverse' => 'معکوس',
            'void' => 'ابطال',
            'lock' => 'قفل',
            'unlock' => 'بازکردن قفل',
            'deny' => 'رد',
            'capture' => 'تسویه',
            'release' => 'آزادسازی',
            'transfer' => 'انتقال',
            'export' => 'خروجی',
            'send' => 'ارسال',
            'sync' => 'همگام‌سازی',
            'retry' => 'تلاش مجدد',
            'redeem' => 'بازخرید',
            'issue' => 'صدور',
            'ingest' => 'دریافت',
            'credit' => 'افزایش موجودی',
            'debit' => 'کاهش موجودی',
            'hold' => 'هولد',
            'diff' => 'مقایسه',
            default => null,
        };
    }
}
